baseURL = 'https://veschin.com'
theme = "PaperMod"
DefaultContentLanguage = "ru"
enableRobotsTXT = true

[params]
author = "Олег Вещин"
description = "Блог про Emacs, Doom Emacs, Linux, Lisp и функциональное программирование"
keywords = ["emacs", "doom emacs", "linux", "lisp", "clojure", "clojurescript"]
images = ["/clojurescript.png"]
DateFormat = "2 January 2006"

[params.schema]
publisherType = "Person"

[params.cover]
responsiveImages = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
style = "doom-one2"

[[menu.main]]
identifier = "github"
name = "My GitHub"
url = "https://github.com/veschin"
weight = 30

[[menu.main]]
identifier = "linkedin"
name = "My Linkedin"
url = "https://linkedin.com/veschin"
weight = 30

[languages.en]
    languageName = 'English'
    title = 'Emacs(Doom)/Linux/Lisp blog'
[languages.en.params]
    description = "Blog about Emacs, Doom Emacs, Linux, Lisp and functional programming"
[languages.ru]
    languageName = 'Русский'
    title = 'Блог про Emacs(Doom)/Linux/Lisp'
